#!/bin/bash
#It's Bouncy!
#syntax: rubberfs [create|mount|attach|unmount|reset|stub] [passphrase] [accesskey] [secretkey] [identifier] [prefix] [mountpoint]
#Stub creates a fake EML instance for apps (e.g. Crystallise) that require it.

action="$1"
passphrase="$2"
accessKey="$3"
secretKey="$4"
identifier="$5"
prefix="$6"
mountpoint="$7"

#reset:
#Warn 10sec
s3backer --reset-mounted-flag --accessId=$accessKey --accessKey=$secretKey --baseURL=https://s3.us.archive.org/ --prefix=$prefix --debug --debug-http $identifier --authVersion=aws2 -f

mount:
Check for pending jobs all done: curl "http://s3.us.archive.org/?check_limit=1&accesskey=$accessKey&bucket=$identifier"
s3backer --accessId=$accessId --accessKey=$secretKey --baseURL=https://s3.us.archive.org/ --blockCacheSize=30000 --blockCacheFile=/Wreathe/.Resources/WreatheCloudService/$prefix/LocalCache --blockSize=16M --compress=9 --blockCacheMaxDirty=256 --blockCacheWriteDelay=40000 --blockCacheThreads=2 --listBlocks --maxRetryPause=600000 --timeout=600 --encrypt --password=$passphrase --prefix=$prefix --size=128T --filename=StorageBlockDevice --debug --debug-http $identifier --defaultContentEncoding="deflate,encrypt-AES-128-CBC" --authVersion=aws2 -f /Wreathe/.Resources/WreatheCloudService/$prefix/dev/
losetup /dev/loop8 /Wreathe/.Resources/WreatheCloudService/$prefix/dev/StorageBlockDevice

#ZFS import instead
fsck -V /dev/loop8
﻿mount -t ext4 /dev/loop8 /Wreathe/.Resources/WreatheCloudService/$prefix/mount/
ln -s /Wreathe/.Resources/WreatheCloudService/$prefix/mount/ $mountpoint


create: mkfs.ext4 -E nodiscard -O 64bit /dev/loop8

unmount: 

umount ﻿/Wreathe/.Resources/WreatheCloudService/$prefix/dev/
wait because of https://github.com/archiecobbs/s3backer/issues/40#issuecomment-94042115)
umount https://s3.us.archive.org/$identifier/$prefix
